Update "CHECK" to exclude packages in "Suggests"
From R-CMD-check on GitHub Actions:
Error: Packages suggested but not available: 'quantmod', 'plotly', 'ggpubr'

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.